language: rust
cache: cargo
addons:
  apt:
    packages:
      - musl-tools
      - python3
      - python3-unittest2
before_install:
  - rustup target add x86_64-unknown-linux-musl
script:
  - make test
