language: rust
cache: /tmp/travis/cargo/csv2html/
addons:
  apt:
    packages:
      - musl-tools
      - python3
before_install:
  - rustup target add x86_64-unknown-linux-musl
script:
  - make test
